server:
  port: 8085
spring:
  application:
    name: feedback-service
  datasource:
    url: jdbc:postgresql://localhost:5434/feedback
    username: feedback
    password: feedback
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/MyShop2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka